### ISSUE TITLE
Missing file needed by `make latex-tables`

### ISSUE THREAD

**Issue by snim2** [softdevteam/pyhyp_experiments#24]
``` bash
$ make latex-tables 
pypy latex_table.py config.py
Traceback (most recent call last):
  File "latex_table.py", line 625, in <module>
    make_tables(config, data_file)
  File "latex_table.py", line 105, in make_tables
    with open(data_file, "r") as data_fh:
IOError: [Errno 2] No such file or directory: 'config_results.json'
Makefile:10: recipe for target 'latex-tables' failed
make: *** [latex-tables] Error 1
```

**Comment by vext01** [comment]
Did you put the results file in place as per the README?

**Comment by snim2** [comment]
The README says: `Alternatively, if you are using the VirtualBox image, then the data from our run can be found in ~/raw_results` but there isn't a `raw_results` directory in this repo.

**Comment by vext01** [comment]
That's only available in the virtualbox image. I linked you to the data earlier. Just copy that in and re-name it.

**Comment by snim2** [comment]
Right, sorry! Thanks...

**Comment by vext01** [comment]
Did you figure this out? Shall we close this?

**Comment by snim2** [comment]
Yes thanks, we're good to close.
